from TweetGenerator import TweetGenerator

class BernieTweets(TweetGenerator):
    tweets = [
        "take health care from canada and create the kind of new world",
        "one of my great fears is a universal health care bill .",
        "republicans control the white house , they control the house . they must end .",
        "the founding fathers gave a strong drugs .",
        "trump ' s reckless shutdown is about the opioid crisis .",
        "i ' m glad that the vote on the white men and women , the white threat in # hatred",
        "disney federal workers are forced to rely on food stamps to survive ?",
        "i have got to stop this fight for all .",
        "young people , you are in jail because they can ' t afford their medications they need",
        "in an unprecedented way , we are looting the end of world .",
        "amazon ’ s warehouses and health care are a fundamental right .",
        "we must not be in jail because they can ' t afford cash bail . unfortunately , once and there are being used to kill civilians because it ' s an agenda .",
        "80 % of fast - food workers have reported experiencing sexual harassment . that is simply unacceptable in the saudi",
        "it ' s time to reduce corporations and dreamers .",
        "the u . s . should not be a family , but ” # medicareforall",
        "there is no border . this is a disgrace .",
        "congratulations to the toys"
        "we have a rigged tax code that has essentially legalized tax",
        "100 years ago west virginia coal miners helped lead .",
        'i want the united states a country are sick and tired of subsidizing them on the worst of the young people in america , who has got to have to give huge tax breaks to billionaires . # taxdebate',
        "if trump decides to say that medicare for all is the way forward get it . it ' s time to repeal the estate tax ? only the top 0 .",
        'do trump and republican leaders believe a full corporation that his wall which the very best the global threat of climate change . # bernieresponds',
        '“ let me respond to the end these protections and everyone else will not be free . it is a a right , not a privilege . # medicareforall',
        'the great economic crisis of reckless .',
        'we have a healthcare system that is not designed to make it easier for people to participate in the richest country in the history of the world .',
        "if we are bold , if we are not go down , but it ' s too late :",
        "mcdonald ’ s gave the new deal . leave the climate change is already destroying the * very little last year .",
        "we ' ll be sure every other major country on earth does that can ' t afford the care of health care .",
        "american airlines made $ 1 . 9 billion in profits . its workers have been a leg up",
        "it ’ s time for congress to step forward to create jobs in the world .",
        "we must do everything we can to stop republicans together .",
        "donald trump ' s choice was a great return on this resolution breast cancer .",
        "the poor and the drug companies have to have health care a right , not a privilege . # medicareforall",
        'not " all " americans — have the money to say .',
        "american billionaires love the military union .",
        "this is a health care crisis no one is coming .",
        "this is what happened : health care for all these huge tax breaks to the top 2 % .",
        "amazon ’ s workplace model is a military and disgrace .",
        "pharma is not just a coincidence for photo ops",
        "republicans say tax cuts for the wealthy and endless planet .",
        "republicans will try to decrease the power of the fossil fuel industry and polluters .",
        "i hope republicans believe in a bill that would make a tax breaks for the rich",
        "it ’ s time to put their workers starvation wages .",
        "jeff bezos is worth $ $ 6 . 7 billion in stock buybacks , but reneged on a commitment to end u . s . support for the disastrous saudi - led war in yemen .",
        "we should not have access to make health care a right .",
        "we allow too many income benefits , is worth $ 160 . 1 billion in his state .",
]

    def getTweet(self, index):
        return self.tweets[index]
